### ISSUE TITLE
Preview not working on forks

### ISSUE THREAD

**Issue by juanfra** [WordPress/action-wp-playground-pr-preview#41]
**Description**

While testing PRs in Twenty Twenty-Five, I've noticed that the link of this action works when the branch is part of the "parent" repository. If a contributor forks the repository, and then creates a PR with their own branch it's not working. Apparently, the theme can't be adequately downloaded in this particular scenario as you can see in the following screencast.

https://github.com/user-attachments/assets/77412b09-2e6d-4a68-8a4f-336a002db0be

**Comment by bgrgicak** [comment]
This is caused by the `repo` parameter. It points to the parent repository while it should point to the forked repository. 


The [repo value](https://github.com/WordPress/action-wp-playground-pr-preview/blob/trunk/src/create-preview-links.ts#L158) comes from here. 

I'm not sure what the best way to resolve this is. We need to find a way to point the repository back to the fork.

**Comment by bgrgicak** [comment]
@juanfra do you have any suggestions how we could resolve this?

**Comment by juanfra** [comment]
@bgrgicak, I didn't have time to look at the code. I can try to save some time towards the end of this week, as I have to prioritize things related to Twenty Twenty-Five first.

**Comment by bgrgicak** [comment]
That would be great, thank you!

**Comment by juanfra** [comment]
@bgrgicak I put something together that could fix it [here](https://github.com/WordPress/action-wp-playground-pr-preview/pull/43).
